[workspace]
resolver = "2"
members = [
  "examples/hello-pebble",
  "pebblesdk",
  "pebblesdk-sys",
]

[workspace.dependencies]
bindgen = "0.71"
cty = "0.2"

pebblesdk = { path = "pebblesdk" }
pebblesdk-sys = { path = "pebblesdk-sys" }
